version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mitz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drinkify
    volumes:
      - ./data:/var/lib/postgresql/data
